name: Not Another Stylist
favicon: null
layout_spectrum: 0.09288158896379173
typography_spectrum: 0.4592236860189587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.22974972776137292
  lightness: 0.09996078023687005
  saturation: 0.6391180146019906
  rhythmicContrast: 0.5649294399190694
purpose: []
